CREATE TABLE IF NOT EXISTE CORE_VENDA (
    ID SERIAL PRIMARY KEY,
    ID_VEICULO LONG NOT NULL,
    CPF_CLIENTE VARCHAR(50) NOT NULL,
    STATUS_VENDA VARCHAR(20) CHECK (STATUS_VENDA IN ('PENDENTE','CONCLUIDO', 'CANCELADO')),
    CODIGO_PAGAMENTO VARCHAR(50) NOT NULL,
    DATA_VENDA DATE NOT NULL);

-- INSERE UMA VENDA

INSERT INTO CORE_VENDA (
    ID_VEICULO,
    CPF_CLIENTE,
    STATUS_VENDA,
    CODIGO_PAGAMENTO,
    DATA_VENDA
) VALUES (
             2,
             '123.456.789-00',
             'CONCLUIDO',
             '1QADZAQEWQ/QEWQ',
             CURRENT_DATE
         )